@host=http://localhost:3000

###
# @name auth
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "sing@dev.com",
    "password": "123456"
}

###
@refreshToken = {{auth.response.body.$.data.refresh_token}}
###
@accessToken = {{auth.response.body.$.data.access_token}}

POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "sing",
    "email": "sing@dev.com",
    "password": "123456",
    "password_confirmation": "123456"
}

###
GET {{host}}/healthz HTTP/1.1

###
GET {{host}}/users HTTP/1.1
Content-Type: application/json
Authorization : Bearer {{accessToken}}



###
POST {{host}}/auth/refreshToken HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{refreshToken}}

{
    "token": "{{refreshToken}}"
}

###
PATCH {{host}}/users/profile/0f6a30ad-a4ef-4a9d-b968-8190b840375b  HTTP/1.1
Content-Type: application/json
Authorization : Bearer {{accessToken}}

{
    "languages": [
        {
            "languageCode": "en",
            "name": "kumneung panthong",
            "description": "sing"
        },
        {
            "languageCode": "th",
            "name": "คำนึง พันธ์ทอง",
            "description": "สิงห์"
        }
    ]
}
